#!/bin/sh

##############################################
#  variables
##############################################

# env
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

# files and dirs
SSH_DIR='/etc/ssh'
RC_SCRIPT_FILE='/etc/rc.local'
RC_BACKUP_FILE='/etc/rc.local.bak'
RC_CONF='/etc/rc.conf'
LOADER_CONF='/boot/loader.conf'
WORKING_DIR='/root'
INSTALL_FILE="$WORKING_DIR/installer.sh"
BSDINIT_DIR="$WORKING_DIR/pfsense-cloudinit-master"
VENV_DIR="$BSDINIT_DIR/.venv"

# pfsense cloudinit
BSDINIT_URL='https://github.com/rrbarreto/pfsense-cloudinit/archive/master.tar.gz'

# commands
VERIFY_PEER='--ca-cert=/usr/local/share/certs/ca-root-nss.crt'
FETCH="fetch ${VERIFY_PEER}"

INSTALL_PKGS='
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-pip-9.0.3.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-pytz-2018.5,1.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-Babel-2.6.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-six-1.11.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-enum34-1.1.6.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-asn1crypto-0.22.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-pycparser-2.18.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-cffi-1.11.5.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-rfc3986-1.1.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-idna-2.7.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-ipaddress-1.0.22.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-cryptography-2.3.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-wrapt-1.10.11.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-funcsigs-1.0.2.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-pyjwt-1.4.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-blinker-1.4.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-debtcollector-1.9.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-oslo.i18n-3.21.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-enum-compat-0.0.2.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-pbr-3.1.1.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-iso8601-0.1.11.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-greenlet-0.4.15.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-eventlet-0.22.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-netaddr-0.7.19.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-serial-3.4.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-stevedore-1.29.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-yaml-3.13.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-oslo.config-6.4.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-oauthlib-1.1.2.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-netifaces-0.10.6.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-tzlocal-1.5.1.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-dnspython-1.15.0.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-monotonic-1.5.txz
http://pkg.freebsd.org/freebsd:11:x86:64/latest/All/py27-argparse-1.4.0.txz
	'


##############################################
#  utils
##############################################
	
echo_debug() {
	echo '[debug] '$1
}
echo_bsdinit_stamp() {
	echo '# Generated by pfsense-cloudinit-installer '`date +'%Y/%m/%d %T'`
}


##############################################
#  main block
##############################################

# Get freebsd version
if uname -K > /dev/null 2>&1
then
	BSD_VERSION=`uname -K`
else
	_BSD_VERSION=`uname -r | cut -d'-' -f 1`
	BSD_VERSION=$(printf "%d%02d%03d" `echo ${_BSD_VERSION} | cut -d'.' -f 1` `echo ${_BSD_VERSION} | cut -d'.' -f 2` 0)
fi

if [ $BSDINIT_DEBUG ]
then
	echo_debug "BSD_VERSION = $BSD_VERSION"
	BSDINIT_SCRIPT_DEBUG_FLAG='--debug'
fi

# Raise unsupport error
[ "$BSD_VERSION" -lt 903000 ] && {
	echo 'Oops! Your freebsd version is too old and not supported!'
	exit 1
}

# Install our prerequisites
export ASSUME_ALWAYS_YES=yes
pkg add $INSTALL_PKGS

[ ! `which python2.7` ] && {
	echo 'python2.7 Not Found !'
	exit 1
}

$FETCH -o - $BSDINIT_URL | tar -xzvf - -C $WORKING_DIR

#virtualenv $VENV_DIR --system-site-packages
#. "$VENV_DIR/bin/activate"
#PYTHON="$VENV_DIR/bin/python"
#pip install --upgrade pip
#pip install -r "$BSDINIT_DIR/requirements.txt"

rm -vf $SSH_DIR/ssh_host*

touch $RC_SCRIPT_FILE
cp -pf $RC_SCRIPT_FILE $RC_BACKUP_FILE
echo_bsdinit_stamp >> $RC_SCRIPT_FILE
echo "(
	/usr/local/bin/python2.7 $BSDINIT_DIR/run.py --log-file /tmp/cloudinit.log $BSDINIT_SCRIPT_DEBUG_FLAG
	cp -pf $RC_BACKUP_FILE $RC_SCRIPT_FILE
	rm -r $BSDINIT_DIR
	rm $RC_BACKUP_FILE
	rm $INSTALL_FILE
)" >> $RC_SCRIPT_FILE

# Output to OpenStack console log
echo_bsdinit_stamp >> $LOADER_CONF
echo 'console="comconsole,vidconsole"' >> $LOADER_CONF
# Bootloader menu delay
echo 'autoboot_delay="1"' >> $LOADER_CONF

if [ $BSDINIT_DEBUG ]
then
	sed -I '' '/^console/d' $LOADER_CONF
fi

echo_bsdinit_stamp >> $RC_CONF
# Get the active NIC and set it to use dhcp
for i in `ifconfig -u -l`
do
	case $i in
		'lo0')
			;;
		'plip0')
			;;
		'pflog0')
			;;
		*)
			echo 'ifconfig_'${i}'="DHCP"' >> $RC_CONF
			break;
			;;
	esac
done
# Enabel sshd in rc.conf
if ! /usr/bin/egrep '^sshd_enable' $RC_CONF > /dev/null
then
	echo 'sshd_enable="YES"' >> $RC_CONF
fi

# Allow %wheel to become root with no password
#sed -i '' 's/# %wheel ALL=(ALL) NOPASSWD: ALL/%wheel ALL=(ALL) NOPASSWD: ALL/' /usr/local/etc/sudoers

# Readme - clean history
echo '==================================================='
echo 'If you want to clean the tcsh history, please issue'
echo '    # set history = 0'
echo '==================================================='
